### ISSUE TITLE
How do I add auto browser refresh?

### ISSUE THREAD

**Issue by pathetix** [cjkoepke/calvinkoepke-com#3]
I think this might not be related to the theme, but since you are using Gulp..
How do I exactly get my browser to auto reload after every changes made?

I ran into browser-sync but not sure how to integrate it.

**Comment by cjkoepke** [comment]
@pathetix Sorry for the late reply on this. As it's not in the theme, I'm not going to build this in. However, you'd likely add a Gulp task to the `gulpfile.js` to allow setting a watcher in terminal. Try this out:

https://browsersync.io/docs/gulp
